#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --tasks-per-node=12
#SBATCH --job-name=CPPsolve
#SBATCH --time=10:00:00
#SBATCH --output=./out/slurm-%j.out
#

name="GKR_W_2D"
mpiCC $name.cpp -o $name
for p in {1..12}; do
	mpirun -np $p ./$name >> out/out_p_${p}_2.out
done